### ISSUE TITLE
More?

### ISSUE THREAD

**Issue by tamaskis99** [berry64/NukkitEssentials#1]
You can adding more commands (ex.: warp, nick, nuke, home [more options], give, say, etc.)?

**Comment by berry64** [comment]
wow people actually check this :P
i've updated many commands but currently haven't updated the forum and the github since it is not stable yet, i will do it as soon as possible :)

**Comment by Adam1609** [comment]
I love ur plugin, but, could you please update quick?
And by the way could you check this?
2016-8-26 04:09:09 [CRITICAL] "Could not pass event 'cn.nukkit.event.player.PlayerJoinEvent' to 'NEssentials v0.0.1-SNAPSHOT': null on net.berry64.Nukkit.Essentials.Events.Join
2016-8-26 04:09:09 [ALERT] cn.nukkit.utils.EventException
    at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:27)
    at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
    at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:561)
    at cn.nukkit.Player.doFirstSpawn(Player.java:716)
    at cn.nukkit.Player.sendNextChunk(Player.java:667)
    at cn.nukkit.Player.checkNetwork(Player.java:1482)
    at cn.nukkit.Server.tick(Server.java:997)
    at cn.nukkit.Server.tickProcessor(Server.java:785)
    at cn.nukkit.Server.start(Server.java:765)
    at cn.nukkit.Server.<init>(Server.java:456)
    at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.lang.NoClassDefFoundError: cn/nukkit/event/TextContainer
    at net.berry64.Nukkit.Essentials.Events.Join.onPlayerJoin(Join.java:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:25)
    ... 10 more

**Comment by Adam1609** [comment]
Oh, and also, setspawn and spawn get error

**Comment by berry64** [comment]
@Adam1609 Thank you for reporting. this version on GitHub is outdated and i think i really need to update it someday :P too lazy at the moment :D
